= Construction d'une librairie d'utilitaires utilisant l'AOP
:tip-caption: 💡
:note-caption: ℹ️
:warning-caption: ⚠️
:icons: font
:hardbreaks-option:

Préfixé par ✔️, des "checkpoints" pour vous aider à vérifier que vous avez tout bon.

== Objectif

Utiliser la programmation orientée aspect (**A**spect **O**riented **P**rogrammation) pour construire une bibliothèque d'utilitaires réutilisables.

== Prérequis

* Git
* Java 21
* Maven 3.9.x
* (Optionnel, mais fortement recommandé) IntelliJ edition _community_ 2024

'''

* Sur la page du template https://github.com/lernejo/maven-starter-template, cliquer sur "Use this template"
* ⚠️ Renseigner comme nom de dépôt : *java_aop_training*
* Marquer le futur dépôt comme *private*
* Une fois le dépôt créé, installer l'app https://github.com/apps/korekto[Korekto], ou mettre à jour sa configuration afin qu'elle ait accès à ce nouveau dépôt
* Cloner le dépôt en utilisant l'*url SSH*
* La branche par défaut est la branche `main`, vous êtes libre de faire des https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request[Pull Requests], mais seule la branche `main` sera corrigée.

== Partie 1 - Dynamic Proxy

Dans un premier temps, nous allons créer une implémentation d'une fonction de réessaie utilisant un proxy dynamique.

Le but étant de créer une instance qui supportera un certain nombre d'erreur pour les méthodes correctement annotées.


* Créer une nouvelle annotation `fr.lernejo.aop.Retry`
* Cette annotation aura deux paramètres :
** `maxTries` de type `int` et de valeur par défaut `1`
** `errorTypes` de type `Class<? extends Exception>[]`
* Dans le répertoire de test, créer une classe `fr.lernejo.aop.FallibleApi`
* ✔️ Vérifier que l'annotation est utilisable sur une méthode et uniquement sur une méthode, en annotant une méthode de cette dernière classe

* Créer une classe `fr.lernejo.aop.RetryableFactory`
* Y ajouter une méthode publique statique `buildRetryable` prenant en paramètre un paramètre de type `Class<T>` (générique) et retournera une instance de type `T` (générique)
* Cette instance sera créée grâce à `javassist.util.proxy.ProxyFactory`
* Les implémentations de `javassist.util.proxy.MethodFilter` et `javassist.util.proxy.MethodHandler` seront dans des classes à créer dans le même package
* Implémenter `javassist.util.proxy.MethodFilter` de manière à ce que seule les méthodes publiques annotées avec `@Retry` soient considérées
* Implémenter `javassist.util.proxy.MethodHandler` de manière à ce qu'un appel de méthode soit répétée maximum `maxErrorCount` en cas d'erreur
* Si `errorTypes` est vide, déclencher le mécanisme sur `java.lang.Exception` et toutes ses sous-classes
* Sinon déclencher le mécanisme uniquement sur les types spécifiés ainsi que tous leurs sous-types
* Si la méthode déléguée sort en erreur alors que le mécanisme est dans la dernière boucle de rééssaie, lancer la dernière erreur obtenue
* Ces différents cas doivent être testés avec des tests unitaires, en profitant de la classe `fr.lernejo.aop.FallibleApi` comme implémentation de test pour décrire les différents cas possibles
* ✔️ Vérifier que 100% de votre code est testé




== Partie 2 - Spring AOP

Créer un aspect permettant d'enregistrer le nombre d'appels des méthodes publiques.

* Créer une classe publique `fr.lernejo.aop.InvocationTracker`
** cette classe aura (au moins) deux méthodes publiques :
[source,java]
----
public static List<String> detectedMethods() {
    // returns the list of recorded methods
}

/**
 * @param methodQualifiedName of the format packageName.className#methodName, example: {@code fr.lernejo.aop.ServiceA#doSomething}
 */
public static long getInvocationCount(String methodQualifiedName) {
    // returns the number of invocation of the given method, 0 if the method is not known
}
----

* Créer une classe publique `fr.lernejo.aop.CountingAspect`
** Cette classe doit être annotée avec `org.aspectj.lang.annotation.Aspect`
** Cette classe doit définir un https://docs.spring.io/spring-framework/reference/core/aop/ataspectj/pointcuts.html[pointcut] (`@Pointcut`) ciblant toutes les methodes publiques
** Cette classe doit définir un https://docs.spring.io/spring-framework/reference/core/aop/ataspectj/advice.html[advice] de type `@After` qui incrémentera le compteur d'invocation
* Le lien entre ces deux classes se fera via une méthode statique
* Tester le bon fonctionnement de cet aspect demandera :
** Une https://docs.spring.io/spring-framework/reference/core/beans/java/composing-configuration-classes.html[configuration] Spring
** Des beans Spring ayant des méthodes publiques
** D'utiliser `org.springframework.context.annotation.AnnotationConfigApplicationContext` afin de créer un contexte utilisant la configuration de test préalablement créée et de récupérer les beans afin d'invoquer leurs méthodes publiques

